# Generated by Django 4.0.4 on 2022-04-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='public',
            new_name='pub_date',
        ),
    ]
